import {
  AudioLines,
  Camera,
  CircleUserRound,
  Clapperboard,
  Eraser,
  Expand,
  Film,
  GalleryHorizontalEnd,
  Globe2,
  ImageIcon,
  ImagePlus,
  Languages,
  Layers3,
  LibraryBig,
  Maximize2,
  MessageCircle,
  Mic2,
  MoveRight,
  Music2,
  Orbit,
  Palette,
  PanelsTopLeft,
  Pencil,
  Radar,
  ScanFace,
  Scissors,
  UserRoundCog,
  UserRoundPen,
  Sparkles,
  SunMedium,
  UsersRound,
  Video,
  WandSparkles,
  Zap,
  type LucideProps,
} from "lucide-react";

const iconMap = {
  clapperboard: Clapperboard,
  film: Film,
  wand: WandSparkles,
  scissors: Scissors,
  panels: PanelsTopLeft,
  sun: SunMedium,
  zap: Zap,
  message: MessageCircle,
  maximize: Maximize2,
  user: CircleUserRound,
  userCog: UserRoundCog,
  userPen: UserRoundPen,
  move: MoveRight,
  audio: AudioLines,
  palette: Palette,
  image: ImageIcon,
  gallery: GalleryHorizontalEnd,
  pencil: Pencil,
  expand: Expand,
  sparkle: Sparkles,
  eraser: Eraser,
  imagePlus: ImagePlus,
  layers: Layers3,
  camera: Camera,
  face: ScanFace,
  mic: Mic2,
  languages: Languages,
  music: Music2,
  world: Globe2,
  orbit: Orbit,
  radar: Radar,
  users: UsersRound,
  library: LibraryBig,
  video: Video,
} as const;

export type ToolIconName = keyof typeof iconMap;

export function ToolIcon({ name, ...props }: { name?: ToolIconName } & LucideProps) {
  const Icon = iconMap[name || "sparkle"] || Sparkles;
  return <Icon aria-hidden="true" {...props} />;
}
